### ISSUE TITLE
I cannot pull your image ，when i use the command" docker pull docker.pkg.github.com/cun-bjy/walkyto-rl/rl-gym", i have told unauthorized.

### ISSUE THREAD

**Issue by chenxiaohua20140401** [CUN-bjy/WalkYTo-rl-gym#4]

**Comment by dion-jy** [comment]
Hi,
recently the name of repo was changed from `walkyto-rl` to `walkyto-rl-gym`.
maybe that would make the problem.

and for your authorization, you should get the token from github.

you can follow the description of package. [link](https://github.com/CUN-bjy/WalkYTo-rl-gym/packages/278485)

here's the guide.
1. get the token from github. [link](https://github.com/settings/tokens/)
2. type below's command. `USERNAME` is your github ID and the `GITHUB_TOKEN` is from yours. 
```bash
sudo docker login http://docker.pkg.github.com/ -u $USERNAME -p $GITHUB_TOKEN
docker pull docker.pkg.github.com/cun-bjy/walkyto-rl-gym/rl-gym:0.1
```

Thanks for using this package. I will fixed the description of the repo.
If you need any help, reply agin.

**Comment by chenxiaohua20140401** [comment]
ok  thankyou, i have solve this problem.

**Comment by dion-jy** [comment]
good, I will close this issue.
